### PR TITLE
Update to Bach 17-ea-3

### PR DESCRIPTION
**Pull request by sormuras**
Experimenting with new `ProjectInfo` structure: dedicated, nested annotations.

Also added support for events that trigger custom code paths: `Bach.OnTestsSuccessful` and `Bach.OnTestsFailed`.

### CODE REVIEW

**Comment by michael-simons** [comment]
Pro: 
- I like the new interface a lot
- Excellent names for external modules and libraries.


Neutral: I liked the flat as it where. But I see the need for structure in the future. Best choice here is main / test space. 
negative: only the qualified annotations in the module info. But that’s up to the project anyway

Open: will the different spaces support different set of libs and modules?

**Comment by sormuras** [comment]
Thanks for the feedback!

I'm with you, regarding the flat structure - perhaps, I'll merge "options" and/or "main" back into the top-level. But I wanted to see the fully-nested version in one or two real projects, first.

> only the qualified annotations in the module info

What do you mean with "only the qualified annotations"?

> will the different spaces support different set of libs and modules?

No, that's not planned. All external modules are stored in a single directory: keep building simple and all 3rd-party modules plain in sight.

**Comment by sormuras** [comment]
🧩 https://github.com/sormuras/bach/issues/227#issuecomment-813611802

**Comment by michael-simons** [comment]
I prefer `@Options` with an import instead of `@ProjectInfo.Options` but that’s just taste. 

Delegating to the service loader for order is excellent.

**Comment by sormuras** [comment]
> I prefer `@Options` with an import instead of `@ProjectInfo.Options` but that’s just taste.

Now, I got it. And I'm with your intial answer here, as well:

> But that’s up to the project anyway

**Comment by sormuras** [comment]
... preparing an upgrade to Bach `17-M1`.

**Pull request closed without merging**
